### ISSUE TITLE
Shifter 

### ISSUE THREAD

**Issue by luki343** [projectgus/car_hacking#1]
Hey,
I had question about shifter (from f30), after connecting 12V to pin 10 (main power) and 7 (wakeup), and GND to pin 8, it should start sending CAN messages on one of the canbus? or is it waiting for some "wakeup" message?

I connected it to arduino with your code hoping it would atleast light up but nothing... Maybe shifter is dead?

**Comment by projectgus** [comment]
Hi @luki343,

It doesn't light up or otherwise change appearance with power, but it should start sending the two CAN messages described here:
https://www.projectgus.com/2022/06/bmw-f-series-gear-selector-part-one-failures#can-output

If you're not receiving any CAN messages then possibly the CAN bus isn't terminated properly (no termination in the GWS so ideally should apply 120 ohms across the bus externally), the Arduino has the wrong baud rate setting or some CAN receiver filter setting is set incorrectly?

**Comment by luki343** [comment]
I tried both CAN buses, one is terminated with 120ohm, the other is not. Checked mcp (500kbs, 8mhz, 120ohm jumper) and everything else looks fine. Idk why it doesnt work. Just ordered second shifter maybe its something wrong with this one.

**Comment by projectgus** [comment]
@luki343 Did you figure this out? Please leave a comment if you did, for anyone who stumbles across this in the future.

**Comment by luki343** [comment]
Yes and no, finally I just used read CAN from some library and all fault was my MCP2515, sometimes it was working sometimes not... chinese sh**, second MCP works ok.
